name: slack-notification

on: [pull_request, issues]

jobs:
  slack-notification:
    runs-on: ubuntu-20.04
    name: Send-Slack-Message
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v1.1.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: ess-devops
          slack-text: Hello! Event *${{ github.event_name }}* in *${{ github.repository }}*
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
