name: SlackNotifications

on:
  pull_request:
    branches: [ development ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Slack Message
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: hbfernandes/slack-action@1.0
      with:
        args: '{\"channel\":\"ess-devops\",\"text\":\"Hello\"}'
