name: SlackNotifications

on:
  issues:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
      - name: Send mail
        uses: timheuer/issue-notifier@v1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        with:
          fromMailAddress: 'martinko.nguyen@gmail.com'
          toMailAddress: 'martinko.nguyen@gmail.com'
          subject: 'A new issue was labeled'
          labelsToMonitor: 'breaking-change,major-bug'
