name: SlackNotifications

on:
  pull_request:
    branches: [ development ]

jobs:
  notifySlack:

    runs-on: ubuntu-latest

    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: abinoda/slack-action@v1.0.7
      with:
        args: '{\"channel\":\"C01G4GGEEF5\",\"Text\":\"Hello\"}'
